<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['id' => 1, 'name' => 'Indonesia', 'iso2' => 'ID', 'iso3' => 'IDN', 'currency_code' => 'IDR', 'region' => 'Asia', 'capital' => 'Jakarta', 'latitude' => -5.000000, 'longitude' => 120.000000],
            ['id' => 2, 'name' => 'Germany', 'iso2' => 'DE', 'iso3' => 'DEU', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Berlin', 'latitude' => 51.000000, 'longitude' => 9.000000],
            ['id' => 3, 'name' => 'China', 'iso2' => 'CN', 'iso3' => 'CHN', 'currency_code' => 'CNY', 'region' => 'Asia', 'capital' => 'Beijing', 'latitude' => 35.000000, 'longitude' => 105.000000],
            ['id' => 4, 'name' => 'Australia', 'iso2' => 'AU', 'iso3' => 'AUS', 'currency_code' => 'AUD', 'region' => 'Oceania', 'capital' => 'Canberra', 'latitude' => -27.000000, 'longitude' => 133.000000],
            ['id' => 5, 'name' => 'Japan', 'iso2' => 'JP', 'iso3' => 'JPN', 'currency_code' => 'JPY', 'region' => 'Asia', 'capital' => 'Tokyo', 'latitude' => 36.000000, 'longitude' => 138.000000],
            ['id' => 6, 'name' => 'France', 'iso2' => 'FR', 'iso3' => 'FRA', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Paris', 'latitude' => 46.000000, 'longitude' => 2.000000],
            ['id' => 7, 'name' => 'Italy', 'iso2' => 'IT', 'iso3' => 'ITA', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Rome', 'latitude' => 42.833333, 'longitude' => 12.833333],
            ['id' => 8, 'name' => 'Spain', 'iso2' => 'ES', 'iso3' => 'ESP', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Madrid', 'latitude' => 40.000000, 'longitude' => -4.000000],
            ['id' => 9, 'name' => 'Canada', 'iso2' => 'CA', 'iso3' => 'CAN', 'currency_code' => 'CAD', 'region' => 'Americas', 'capital' => 'Ottawa', 'latitude' => 60.000000, 'longitude' => -95.000000],
            ['id' => 10, 'name' => 'Brazil', 'iso2' => 'BR', 'iso3' => 'BRA', 'currency_code' => 'BRL', 'region' => 'Americas', 'capital' => 'Brasília', 'latitude' => -10.000000, 'longitude' => -55.000000],
            ['id' => 11, 'name' => 'Mexico', 'iso2' => 'MX', 'iso3' => 'MEX', 'currency_code' => 'MXN', 'region' => 'Americas', 'capital' => 'Mexico City', 'latitude' => 23.000000, 'longitude' => -102.000000],
            ['id' => 13, 'name' => 'Russian Federation', 'iso2' => 'RU', 'iso3' => 'RUS', 'currency_code' => 'RUB', 'region' => 'Europe', 'capital' => 'Moscow', 'latitude' => 60.000000, 'longitude' => 100.000000],
            ['id' => 14, 'name' => 'Netherlands', 'iso2' => 'NL', 'iso3' => 'NLD', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Amsterdam', 'latitude' => 52.500000, 'longitude' => 5.750000],
            ['id' => 15, 'name' => 'Switzerland', 'iso2' => 'CH', 'iso3' => 'CHE', 'currency_code' => 'CHF', 'region' => 'Europe', 'capital' => 'Bern', 'latitude' => 47.000000, 'longitude' => 8.000000],
            ['id' => 16, 'name' => 'Sweden', 'iso2' => 'SE', 'iso3' => 'SWE', 'currency_code' => 'SEK', 'region' => 'Europe', 'capital' => 'Stockholm', 'latitude' => 62.000000, 'longitude' => 15.000000],
            ['id' => 17, 'name' => 'Norway', 'iso2' => 'NO', 'iso3' => 'NOR', 'currency_code' => 'NOK', 'region' => 'Europe', 'capital' => 'Oslo', 'latitude' => 62.000000, 'longitude' => 10.000000],
            ['id' => 18, 'name' => 'Denmark', 'iso2' => 'DK', 'iso3' => 'DNK', 'currency_code' => 'DKK', 'region' => 'Europe', 'capital' => 'Copenhagen', 'latitude' => 56.000000, 'longitude' => 10.000000],
            ['id' => 19, 'name' => 'Finland', 'iso2' => 'FI', 'iso3' => 'FIN', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Helsinki', 'latitude' => 64.000000, 'longitude' => 26.000000],
            ['id' => 20, 'name' => 'Poland', 'iso2' => 'PL', 'iso3' => 'POL', 'currency_code' => 'PLN', 'region' => 'Europe', 'capital' => 'Warsaw', 'latitude' => 52.000000, 'longitude' => 20.000000],
            ['id' => 21, 'name' => 'Portugal', 'iso2' => 'PT', 'iso3' => 'PRT', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Lisbon', 'latitude' => 39.500000, 'longitude' => -8.000000],
            ['id' => 22, 'name' => 'Greece', 'iso2' => 'GR', 'iso3' => 'GRC', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Athens', 'latitude' => 39.000000, 'longitude' => 22.000000],
            ['id' => 23, 'name' => 'Turkey', 'iso2' => 'TR', 'iso3' => 'TUR', 'currency_code' => 'TRY', 'region' => 'Asia', 'capital' => 'Ankara', 'latitude' => 39.000000, 'longitude' => 35.000000],
            ['id' => 24, 'name' => 'Egypt', 'iso2' => 'EG', 'iso3' => 'EGY', 'currency_code' => 'EGP', 'region' => 'Africa', 'capital' => 'Cairo', 'latitude' => 27.000000, 'longitude' => 30.000000],
            ['id' => 25, 'name' => 'Israel', 'iso2' => 'IL', 'iso3' => 'ISR', 'currency_code' => 'ILS', 'region' => 'Asia', 'capital' => 'Jerusalem', 'latitude' => 31.500000, 'longitude' => 34.750000],
            ['id' => 26, 'name' => 'Nigeria', 'iso2' => 'NG', 'iso3' => 'NGA', 'currency_code' => 'NGN', 'region' => 'Africa', 'capital' => 'Abuja', 'latitude' => 10.000000, 'longitude' => 8.000000],
            ['id' => 27, 'name' => 'Kenya', 'iso2' => 'KE', 'iso3' => 'KEN', 'currency_code' => 'KES', 'region' => 'Africa', 'capital' => 'Nairobi', 'latitude' => 1.000000, 'longitude' => 38.000000],
            ['id' => 28, 'name' => 'Morocco', 'iso2' => 'MA', 'iso3' => 'MAR', 'currency_code' => 'MAD', 'region' => 'Africa', 'capital' => 'Rabat', 'latitude' => 32.000000, 'longitude' => -5.000000],
            ['id' => 29, 'name' => 'Argentina', 'iso2' => 'AR', 'iso3' => 'ARG', 'currency_code' => 'ARS', 'region' => 'Americas', 'capital' => 'Buenos Aires', 'latitude' => -34.000000, 'longitude' => -64.000000],
            ['id' => 30, 'name' => 'Chile', 'iso2' => 'CL', 'iso3' => 'CHL', 'currency_code' => 'CLP', 'region' => 'Americas', 'capital' => 'Santiago', 'latitude' => -30.000000, 'longitude' => -71.000000],
            ['id' => 31, 'name' => 'Colombia', 'iso2' => 'CO', 'iso3' => 'COL', 'currency_code' => 'COP', 'region' => 'Americas', 'capital' => 'Bogotá', 'latitude' => 4.000000, 'longitude' => -72.000000],
            ['id' => 32, 'name' => 'Peru', 'iso2' => 'PE', 'iso3' => 'PER', 'currency_code' => 'PEN', 'region' => 'Americas', 'capital' => 'Lima', 'latitude' => -10.000000, 'longitude' => -76.000000],
            ['id' => 33, 'name' => 'Venezuela', 'iso2' => 'VE', 'iso3' => 'VEN', 'currency_code' => 'VEF', 'region' => 'Americas', 'capital' => 'Caracas', 'latitude' => 8.000000, 'longitude' => -66.000000],
            ['id' => 34, 'name' => 'Thailand', 'iso2' => 'TH', 'iso3' => 'THA', 'currency_code' => 'THB', 'region' => 'Asia', 'capital' => 'Bangkok', 'latitude' => 15.000000, 'longitude' => 100.000000],
            ['id' => 35, 'name' => 'Vietnam', 'iso2' => 'VN', 'iso3' => 'VNM', 'currency_code' => 'VND', 'region' => 'Asia', 'capital' => 'Hanoi', 'latitude' => 16.166666, 'longitude' => 107.833333],
            ['id' => 36, 'name' => 'Philippines', 'iso2' => 'PH', 'iso3' => 'PHL', 'currency_code' => 'PHP', 'region' => 'Asia', 'capital' => 'Manila', 'latitude' => 13.000000, 'longitude' => 122.000000],
            ['id' => 37, 'name' => 'Malaysia', 'iso2' => 'MY', 'iso3' => 'MYS', 'currency_code' => 'MYR', 'region' => 'Asia', 'capital' => 'Kuala Lumpur', 'latitude' => 2.500000, 'longitude' => 112.500000],
            ['id' => 38, 'name' => 'Singapore', 'iso2' => 'SG', 'iso3' => 'SGP', 'currency_code' => 'SGD', 'region' => 'Asia', 'capital' => 'Singapore', 'latitude' => 1.366666, 'longitude' => 103.800000],
            ['id' => 39, 'name' => 'Ireland', 'iso2' => 'IE', 'iso3' => 'IRL', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Dublin', 'latitude' => 53.000000, 'longitude' => -8.000000],
            ['id' => 40, 'name' => 'Belgium', 'iso2' => 'BE', 'iso3' => 'BEL', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Brussels', 'latitude' => 50.833333, 'longitude' => 4.000000],
            ['id' => 41, 'name' => 'Austria', 'iso2' => 'AT', 'iso3' => 'AUT', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Vienna', 'latitude' => 47.333333, 'longitude' => 13.333333],
            ['id' => 42, 'name' => 'Hungary', 'iso2' => 'HU', 'iso3' => 'HUN', 'currency_code' => 'HUF', 'region' => 'Europe', 'capital' => 'Budapest', 'latitude' => 47.000000, 'longitude' => 20.000000],
            ['id' => 43, 'name' => 'Romania', 'iso2' => 'RO', 'iso3' => 'ROU', 'currency_code' => 'RON', 'region' => 'Europe', 'capital' => 'Bucharest', 'latitude' => 46.000000, 'longitude' => 25.000000],
            ['id' => 44, 'name' => 'Ukraine', 'iso2' => 'UA', 'iso3' => 'UKR', 'currency_code' => 'UAH', 'region' => 'Europe', 'capital' => 'Kyiv', 'latitude' => 49.000000, 'longitude' => 32.000000],
            ['id' => 45, 'name' => 'Pakistan', 'iso2' => 'PK', 'iso3' => 'PAK', 'currency_code' => 'PKR', 'region' => 'Asia', 'capital' => 'Islamabad', 'latitude' => 30.000000, 'longitude' => 70.000000],
            ['id' => 46, 'name' => 'Bangladesh', 'iso2' => 'BD', 'iso3' => 'BGD', 'currency_code' => 'BDT', 'region' => 'Asia', 'capital' => 'Dhaka', 'latitude' => 24.000000, 'longitude' => 90.000000],
            ['id' => 47, 'name' => 'Iran', 'iso2' => 'IR', 'iso3' => 'IRN', 'currency_code' => 'IRR', 'region' => 'Asia', 'capital' => 'Tehran', 'latitude' => 32.000000, 'longitude' => 53.000000],
            ['id' => 48, 'name' => 'Iraq', 'iso2' => 'IQ', 'iso3' => 'IRQ', 'currency_code' => 'IQD', 'region' => 'Asia', 'capital' => 'Baghdad', 'latitude' => 33.000000, 'longitude' => 44.000000],
            ['id' => 49, 'name' => 'Jordan', 'iso2' => 'JO', 'iso3' => 'JOR', 'currency_code' => 'JOD', 'region' => 'Asia', 'capital' => 'Amman', 'latitude' => 31.000000, 'longitude' => 36.000000],
            ['id' => 50, 'name' => 'Lebanon', 'iso2' => 'LB', 'iso3' => 'LBN', 'currency_code' => 'LBP', 'region' => 'Asia', 'capital' => 'Beirut', 'latitude' => 33.833333, 'longitude' => 35.833333],
            ['id' => 51, 'name' => 'Qatar', 'iso2' => 'QA', 'iso3' => 'QAT', 'currency_code' => 'QAR', 'region' => 'Asia', 'capital' => 'Doha', 'latitude' => 25.500000, 'longitude' => 51.250000],
            ['id' => 52, 'name' => 'Kuwait', 'iso2' => 'KW', 'iso3' => 'KWT', 'currency_code' => 'KWD', 'region' => 'Asia', 'capital' => 'Kuwait City', 'latitude' => 29.500000, 'longitude' => 45.750000],
            ['id' => 53, 'name' => 'Oman', 'iso2' => 'OM', 'iso3' => 'OMN', 'currency_code' => 'OMR', 'region' => 'Asia', 'capital' => 'Muscat', 'latitude' => 21.000000, 'longitude' => 57.000000],
            ['id' => 54, 'name' => 'Bahrain', 'iso2' => 'BH', 'iso3' => 'BHR', 'currency_code' => 'BHD', 'region' => 'Asia', 'capital' => 'Manama', 'latitude' => 26.000000, 'longitude' => 50.550000],
            ['id' => 55, 'name' => 'Kazakhstan', 'iso2' => 'KZ', 'iso3' => 'KAZ', 'currency_code' => 'KZT', 'region' => 'Asia', 'capital' => 'Nur-Sultan', 'latitude' => 48.000000, 'longitude' => 68.000000],
            ['id' => 56, 'name' => 'Uzbekistan', 'iso2' => 'UZ', 'iso3' => 'UZB', 'currency_code' => 'UZS', 'region' => 'Asia', 'capital' => 'Tashkent', 'latitude' => 41.000000, 'longitude' => 64.000000],
            ['id' => 57, 'name' => 'Mongolia', 'iso2' => 'MN', 'iso3' => 'MNG', 'currency_code' => 'MNT', 'region' => 'Asia', 'capital' => 'Ulan Bator', 'latitude' => 46.000000, 'longitude' => 105.000000],
            ['id' => 58, 'name' => 'Myanmar', 'iso2' => 'MM', 'iso3' => 'MMR', 'currency_code' => 'MMK', 'region' => 'Asia', 'capital' => 'Naypyidaw', 'latitude' => 22.000000, 'longitude' => 98.000000],
            ['id' => 59, 'name' => 'Cambodia', 'iso2' => 'KH', 'iso3' => 'KHM', 'currency_code' => 'KHR', 'region' => 'Asia', 'capital' => 'Phnom Penh', 'latitude' => 13.000000, 'longitude' => 105.000000],
            ['id' => 60, 'name' => 'Nepal', 'iso2' => 'NP', 'iso3' => 'NPL', 'currency_code' => 'NPR', 'region' => 'Asia', 'capital' => 'Kathmandu', 'latitude' => 28.000000, 'longitude' => 84.000000],
            ['id' => 61, 'name' => 'Bhutan', 'iso2' => 'BT', 'iso3' => 'BTN', 'currency_code' => 'BTN', 'region' => 'Asia', 'capital' => 'Thimphu', 'latitude' => 27.500000, 'longitude' => 90.500000],
            ['id' => 62, 'name' => 'Sudan', 'iso2' => 'SD', 'iso3' => 'SDN', 'currency_code' => 'SDG', 'region' => 'Africa', 'capital' => 'Khartoum', 'latitude' => 15.000000, 'longitude' => 30.000000],
            ['id' => 63, 'name' => 'Ethiopia', 'iso2' => 'ET', 'iso3' => 'ETH', 'currency_code' => 'ETB', 'region' => 'Africa', 'capital' => 'Addis Ababa', 'latitude' => 8.000000, 'longitude' => 38.000000],
            ['id' => 64, 'name' => 'Ghana', 'iso2' => 'GH', 'iso3' => 'GHA', 'currency_code' => 'GHS', 'region' => 'Africa', 'capital' => 'Accra', 'latitude' => 8.000000, 'longitude' => -2.000000],
            ['id' => 65, 'name' => 'Tanzania', 'iso2' => 'TZ', 'iso3' => 'TZA', 'currency_code' => 'TZS', 'region' => 'Africa', 'capital' => 'Dodoma', 'latitude' => -6.000000, 'longitude' => 35.000000],
            ['id' => 66, 'name' => 'Uganda', 'iso2' => 'UG', 'iso3' => 'UGA', 'currency_code' => 'UGX', 'region' => 'Africa', 'capital' => 'Kampala', 'latitude' => 1.000000, 'longitude' => 32.000000],
            ['id' => 67, 'name' => 'Zimbabwe', 'iso2' => 'ZW', 'iso3' => 'ZWE', 'currency_code' => 'ZMW', 'region' => 'Africa', 'capital' => 'Harare', 'latitude' => -20.000000, 'longitude' => 30.000000],
            ['id' => 68, 'name' => 'Zambia', 'iso2' => 'ZM', 'iso3' => 'ZMB', 'currency_code' => 'ZMW', 'region' => 'Africa', 'capital' => 'Lusaka', 'latitude' => -15.000000, 'longitude' => 30.000000],
            ['id' => 69, 'name' => 'Senegal', 'iso2' => 'SN', 'iso3' => 'SEN', 'currency_code' => 'XOF', 'region' => 'Africa', 'capital' => 'Dakar', 'latitude' => 14.000000, 'longitude' => -14.000000],
            ['id' => 70, 'name' => 'Cameroon', 'iso2' => 'CM', 'iso3' => 'CMR', 'currency_code' => 'XAF', 'region' => 'Africa', 'capital' => 'Yaoundé', 'latitude' => 6.000000, 'longitude' => 12.000000],
            ['id' => 71, 'name' => 'Angola', 'iso2' => 'AO', 'iso3' => 'AGO', 'currency_code' => 'AOA', 'region' => 'Africa', 'capital' => 'Luanda', 'latitude' => -12.500000, 'longitude' => 18.500000],
            ['id' => 72, 'name' => 'Mozambique', 'iso2' => 'MZ', 'iso3' => 'MOZ', 'currency_code' => 'MZN', 'region' => 'Africa', 'capital' => 'Maputo', 'latitude' => -18.250000, 'longitude' => 35.000000],
            ['id' => 73, 'name' => 'Algeria', 'iso2' => 'DZ', 'iso3' => 'DZA', 'currency_code' => 'DZD', 'region' => 'Africa', 'capital' => 'Algiers', 'latitude' => 28.000000, 'longitude' => 3.000000],
            ['id' => 74, 'name' => 'Tunisia', 'iso2' => 'TN', 'iso3' => 'TUN', 'currency_code' => 'TND', 'region' => 'Africa', 'capital' => 'Tunis', 'latitude' => 34.000000, 'longitude' => 9.000000],
            ['id' => 75, 'name' => 'Libya', 'iso2' => 'LY', 'iso3' => 'LBY', 'currency_code' => 'LYD', 'region' => 'Africa', 'capital' => 'Tripoli', 'latitude' => 25.000000, 'longitude' => 17.000000],
            ['id' => 76, 'name' => 'Iceland', 'iso2' => 'IS', 'iso3' => 'ISL', 'currency_code' => 'ISK', 'region' => 'Europe', 'capital' => 'Reykjavík', 'latitude' => 65.000000, 'longitude' => -18.000000],
            ['id' => 77, 'name' => 'Luxembourg', 'iso2' => 'LU', 'iso3' => 'LUX', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Luxembourg', 'latitude' => 49.750000, 'longitude' => 6.166666],
            ['id' => 78, 'name' => 'Malta', 'iso2' => 'MT', 'iso3' => 'MLT', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Valletta', 'latitude' => 35.833333, 'longitude' => 14.583333],
            ['id' => 79, 'name' => 'Cyprus', 'iso2' => 'CY', 'iso3' => 'CYP', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Nicosia', 'latitude' => 35.000000, 'longitude' => 33.000000],
            ['id' => 80, 'name' => 'Croatia', 'iso2' => 'HR', 'iso3' => 'HRV', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Zagreb', 'latitude' => 45.166666, 'longitude' => 15.500000],
            ['id' => 81, 'name' => 'Serbia', 'iso2' => 'RS', 'iso3' => 'SRB', 'currency_code' => 'RSD', 'region' => 'Europe', 'capital' => 'Belgrade', 'latitude' => 44.000000, 'longitude' => 21.000000],
            ['id' => 82, 'name' => 'Bulgaria', 'iso2' => 'BG', 'iso3' => 'BGR', 'currency_code' => 'BGN', 'region' => 'Europe', 'capital' => 'Sofia', 'latitude' => 43.000000, 'longitude' => 25.000000],
            ['id' => 83, 'name' => 'Slovakia', 'iso2' => 'SK', 'iso3' => 'SVK', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Bratislava', 'latitude' => 48.666666, 'longitude' => 19.500000],
            ['id' => 84, 'name' => 'Slovenia', 'iso2' => 'SI', 'iso3' => 'SVN', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Ljubljana', 'latitude' => 46.116666, 'longitude' => 14.816666],
            ['id' => 85, 'name' => 'Lithuania', 'iso2' => 'LT', 'iso3' => 'LTU', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Vilnius', 'latitude' => 56.000000, 'longitude' => 24.000000],
            ['id' => 86, 'name' => 'Latvia', 'iso2' => 'LV', 'iso3' => 'LVA', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Riga', 'latitude' => 57.000000, 'longitude' => 25.000000],
            ['id' => 87, 'name' => 'Estonia', 'iso2' => 'EE', 'iso3' => 'EST', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Tallinn', 'latitude' => 59.000000, 'longitude' => 26.000000],
            ['id' => 88, 'name' => 'Georgia', 'iso2' => 'GE', 'iso3' => 'GEO', 'currency_code' => 'GEL', 'region' => 'Asia', 'capital' => 'Tbilisi', 'latitude' => 42.000000, 'longitude' => 43.500000],
            ['id' => 89, 'name' => 'Armenia', 'iso2' => 'AM', 'iso3' => 'ARM', 'currency_code' => 'AMD', 'region' => 'Asia', 'capital' => 'Yerevan', 'latitude' => 40.000000, 'longitude' => 45.000000],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(['id' => $country['id']], $country);
        }
    }
}