<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['id' => 1, 'name' => 'Indonesia', 'code' => 'ID', 'currency_code' => 'IDR', 'region' => 'Asia', 'capital' => 'Jakarta', 'latitude' => -5, 'longitude' => 120],
            ['id' => 2, 'name' => 'Germany', 'code' => 'DE', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Berlin', 'latitude' => 51, 'longitude' => 9],
            ['id' => 3, 'name' => 'China', 'code' => 'CN', 'currency_code' => 'CNY', 'region' => 'Asia', 'capital' => 'Beijing', 'latitude' => 35, 'longitude' => 105],
            ['id' => 4, 'name' => 'Australia', 'code' => 'AU', 'currency_code' => 'AUD', 'region' => 'Oceania', 'capital' => 'Canberra', 'latitude' => -27, 'longitude' => 133],
            ['id' => 5, 'name' => 'Japan', 'code' => 'JP', 'currency_code' => 'JPY', 'region' => 'Asia', 'capital' => 'Tokyo', 'latitude' => 36, 'longitude' => 138],
            ['id' => 6, 'name' => 'France', 'code' => 'FR', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Paris', 'latitude' => 46, 'longitude' => 2],
            ['id' => 7, 'name' => 'Italy', 'code' => 'IT', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Rome', 'latitude' => 42.8333, 'longitude' => 12.8333],
            ['id' => 8, 'name' => 'Spain', 'code' => 'ES', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Madrid', 'latitude' => 40, 'longitude' => -4],
            ['id' => 9, 'name' => 'Canada', 'code' => 'CA', 'currency_code' => 'CAD', 'region' => 'Americas', 'capital' => 'Ottawa', 'latitude' => 60, 'longitude' => -95],
            ['id' => 10, 'name' => 'Brazil', 'code' => 'BR', 'currency_code' => 'BRL', 'region' => 'Americas', 'capital' => 'Brasília', 'latitude' => -10, 'longitude' => -55],
            ['id' => 11, 'name' => 'Mexico', 'code' => 'MX', 'currency_code' => 'MXN', 'region' => 'Americas', 'capital' => 'Mexico City', 'latitude' => 23, 'longitude' => -102],
            ['id' => 13, 'name' => 'Russian Federation', 'code' => 'RU', 'currency_code' => 'RUB', 'region' => 'Europe', 'capital' => 'Moscow', 'latitude' => 60, 'longitude' => 100],
            ['id' => 14, 'name' => 'Netherlands', 'code' => 'NL', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Amsterdam', 'latitude' => 52.5, 'longitude' => 5.75],
            ['id' => 15, 'name' => 'Switzerland', 'code' => 'CH', 'currency_code' => 'CHF', 'region' => 'Europe', 'capital' => 'Bern', 'latitude' => 47, 'longitude' => 8],
            ['id' => 16, 'name' => 'Sweden', 'code' => 'SE', 'currency_code' => 'SEK', 'region' => 'Europe', 'capital' => 'Stockholm', 'latitude' => 62, 'longitude' => 15],
            ['id' => 17, 'name' => 'Norway', 'code' => 'NO', 'currency_code' => 'NOK', 'region' => 'Europe', 'capital' => 'Oslo', 'latitude' => 62, 'longitude' => 10],
            ['id' => 18, 'name' => 'Denmark', 'code' => 'DK', 'currency_code' => 'DKK', 'region' => 'Europe', 'capital' => 'Copenhagen', 'latitude' => 56, 'longitude' => 10],
            ['id' => 19, 'name' => 'Finland', 'code' => 'FI', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Helsinki', 'latitude' => 64, 'longitude' => 26],
            ['id' => 20, 'name' => 'Poland', 'code' => 'PL', 'currency_code' => 'PLN', 'region' => 'Europe', 'capital' => 'Warsaw', 'latitude' => 52, 'longitude' => 20],
            ['id' => 21, 'name' => 'Portugal', 'code' => 'PT', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Lisbon', 'latitude' => 39.5, 'longitude' => -8],
            ['id' => 22, 'name' => 'Greece', 'code' => 'GR', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Athens', 'latitude' => 39, 'longitude' => 22],
            ['id' => 23, 'name' => 'Turkey', 'code' => 'TR', 'currency_code' => 'TRY', 'region' => 'Asia', 'capital' => 'Ankara', 'latitude' => 39, 'longitude' => 35],
            ['id' => 24, 'name' => 'Egypt', 'code' => 'EG', 'currency_code' => 'EGP', 'region' => 'Africa', 'capital' => 'Cairo', 'latitude' => 27, 'longitude' => 30],
            ['id' => 25, 'name' => 'Israel', 'code' => 'IL', 'currency_code' => 'ILS', 'region' => 'Asia', 'capital' => 'Jerusalem', 'latitude' => 31.5, 'longitude' => 34.75],
            ['id' => 26, 'name' => 'Nigeria', 'code' => 'NG', 'currency_code' => 'NGN', 'region' => 'Africa', 'capital' => 'Abuja', 'latitude' => 10, 'longitude' => 8],
            ['id' => 27, 'name' => 'Kenya', 'code' => 'KE', 'currency_code' => 'KES', 'region' => 'Africa', 'capital' => 'Nairobi', 'latitude' => 1, 'longitude' => 38],
            ['id' => 28, 'name' => 'Morocco', 'code' => 'MA', 'currency_code' => 'MAD', 'region' => 'Africa', 'capital' => 'Rabat', 'latitude' => 32, 'longitude' => -5],
            ['id' => 29, 'name' => 'Argentina', 'code' => 'AR', 'currency_code' => 'ARS', 'region' => 'Americas', 'capital' => 'Buenos Aires', 'latitude' => -34, 'longitude' => -64],
            ['id' => 30, 'name' => 'Chile', 'code' => 'CL', 'currency_code' => 'CLP', 'region' => 'Americas', 'capital' => 'Santiago', 'latitude' => -30, 'longitude' => -71],
            ['id' => 31, 'name' => 'Colombia', 'code' => 'CO', 'currency_code' => 'COP', 'region' => 'Americas', 'capital' => 'Bogotá', 'latitude' => 4, 'longitude' => -72],
            ['id' => 32, 'name' => 'Peru', 'code' => 'PE', 'currency_code' => 'PEN', 'region' => 'Americas', 'capital' => 'Lima', 'latitude' => -10, 'longitude' => -76],
            ['id' => 33, 'name' => 'Venezuela (Bolivarian Republic of)', 'code' => 'VE', 'currency_code' => 'VEF', 'region' => 'Americas', 'capital' => 'Caracas', 'latitude' => 8, 'longitude' => -66],
            ['id' => 34, 'name' => 'Thailand', 'code' => 'TH', 'currency_code' => 'THB', 'region' => 'Asia', 'capital' => 'Bangkok', 'latitude' => 15, 'longitude' => 100],
            ['id' => 35, 'name' => 'Vietnam', 'code' => 'VN', 'currency_code' => 'VND', 'region' => 'Asia', 'capital' => 'Hanoi', 'latitude' => 16.1666, 'longitude' => 107.8333],
            ['id' => 36, 'name' => 'Philippines', 'code' => 'PH', 'currency_code' => 'PHP', 'region' => 'Asia', 'capital' => 'Manila', 'latitude' => 13, 'longitude' => 122],
            ['id' => 37, 'name' => 'Malaysia', 'code' => 'MY', 'currency_code' => 'MYR', 'region' => 'Asia', 'capital' => 'Kuala Lumpur', 'latitude' => 2.5, 'longitude' => 112.5],
            ['id' => 38, 'name' => 'Singapore', 'code' => 'SG', 'currency_code' => 'SGD', 'region' => 'Asia', 'capital' => 'Singapore', 'latitude' => 1.3666, 'longitude' => 103.8],
            ['id' => 39, 'name' => 'Ireland', 'code' => 'IE', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Dublin', 'latitude' => 53, 'longitude' => -8],
            ['id' => 40, 'name' => 'Belgium', 'code' => 'BE', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Brussels', 'latitude' => 50.8333, 'longitude' => 4],
            ['id' => 41, 'name' => 'Austria', 'code' => 'AT', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Vienna', 'latitude' => 47.3333, 'longitude' => 13.3333],
            ['id' => 42, 'name' => 'Hungary', 'code' => 'HU', 'currency_code' => 'HUF', 'region' => 'Europe', 'capital' => 'Budapest', 'latitude' => 47, 'longitude' => 20],
            ['id' => 43, 'name' => 'Romania', 'code' => 'RO', 'currency_code' => 'RON', 'region' => 'Europe', 'capital' => 'Bucharest', 'latitude' => 46, 'longitude' => 25],
            ['id' => 44, 'name' => 'Ukraine', 'code' => 'UA', 'currency_code' => 'UAH', 'region' => 'Europe', 'capital' => 'Kyiv', 'latitude' => 49, 'longitude' => 32],
            ['id' => 45, 'name' => 'Pakistan', 'code' => 'PK', 'currency_code' => 'PKR', 'region' => 'Asia', 'capital' => 'Islamabad', 'latitude' => 30, 'longitude' => 70],
            ['id' => 46, 'name' => 'Bangladesh', 'code' => 'BD', 'currency_code' => 'BDT', 'region' => 'Asia', 'capital' => 'Dhaka', 'latitude' => 24, 'longitude' => 90],
            ['id' => 47, 'name' => 'Iran (Islamic Republic of)', 'code' => 'IR', 'currency_code' => 'IRR', 'region' => 'Asia', 'capital' => 'Tehran', 'latitude' => 32, 'longitude' => 53],
            ['id' => 48, 'name' => 'Iraq', 'code' => 'IQ', 'currency_code' => 'IQD', 'region' => 'Asia', 'capital' => 'Baghdad', 'latitude' => 33, 'longitude' => 44],
            ['id' => 49, 'name' => 'Jordan', 'code' => 'JO', 'currency_code' => 'JOD', 'region' => 'Asia', 'capital' => 'Amman', 'latitude' => 31, 'longitude' => 36],
            ['id' => 50, 'name' => 'Lebanon', 'code' => 'LB', 'currency_code' => 'LBP', 'region' => 'Asia', 'capital' => 'Beirut', 'latitude' => 33.8333, 'longitude' => 35.8333],
            ['id' => 51, 'name' => 'Qatar', 'code' => 'QA', 'currency_code' => 'QAR', 'region' => 'Asia', 'capital' => 'Doha', 'latitude' => 25.5, 'longitude' => 51.25],
            ['id' => 52, 'name' => 'Kuwait', 'code' => 'KW', 'currency_code' => 'KWD', 'region' => 'Asia', 'capital' => 'Kuwait City', 'latitude' => 29.5, 'longitude' => 45.75],
            ['id' => 53, 'name' => 'Oman', 'code' => 'OM', 'currency_code' => 'OMR', 'region' => 'Asia', 'capital' => 'Muscat', 'latitude' => 21, 'longitude' => 57],
            ['id' => 54, 'name' => 'Bahrain', 'code' => 'BH', 'currency_code' => 'BHD', 'region' => 'Asia', 'capital' => 'Manama', 'latitude' => 26, 'longitude' => 50.55],
            ['id' => 55, 'name' => 'Kazakhstan', 'code' => 'KZ', 'currency_code' => 'KZT', 'region' => 'Asia', 'capital' => 'Nur-Sultan', 'latitude' => 48, 'longitude' => 68],
            ['id' => 56, 'name' => 'Uzbekistan', 'code' => 'UZ', 'currency_code' => 'UZS', 'region' => 'Asia', 'capital' => 'Tashkent', 'latitude' => 41, 'longitude' => 64],
            ['id' => 57, 'name' => 'Mongolia', 'code' => 'MN', 'currency_code' => 'MNT', 'region' => 'Asia', 'capital' => 'Ulan Bator', 'latitude' => 46, 'longitude' => 105],
            ['id' => 58, 'name' => 'Myanmar', 'code' => 'MM', 'currency_code' => 'MMK', 'region' => 'Asia', 'capital' => 'Naypyidaw', 'latitude' => 22, 'longitude' => 98],
            ['id' => 59, 'name' => 'Cambodia', 'code' => 'KH', 'currency_code' => 'KHR', 'region' => 'Asia', 'capital' => 'Phnom Penh', 'latitude' => 13, 'longitude' => 105],
            ['id' => 60, 'name' => 'Nepal', 'code' => 'NP', 'currency_code' => 'NPR', 'region' => 'Asia', 'capital' => 'Kathmandu', 'latitude' => 28, 'longitude' => 84],
            ['id' => 61, 'name' => 'Bhutan', 'code' => 'BT', 'currency_code' => 'BTN', 'region' => 'Asia', 'capital' => 'Thimphu', 'latitude' => 27.5, 'longitude' => 90.5],
            ['id' => 62, 'name' => 'Sudan', 'code' => 'SD', 'currency_code' => 'SDG', 'region' => 'Africa', 'capital' => 'Khartoum', 'latitude' => 15, 'longitude' => 30],
            ['id' => 63, 'name' => 'Ethiopia', 'code' => 'ET', 'currency_code' => 'ETB', 'region' => 'Africa', 'capital' => 'Addis Ababa', 'latitude' => 8, 'longitude' => 38],
            ['id' => 64, 'name' => 'Ghana', 'code' => 'GH', 'currency_code' => 'GHS', 'region' => 'Africa', 'capital' => 'Accra', 'latitude' => 8, 'longitude' => -2],
            ['id' => 65, 'name' => 'Tanzania, United Republic of', 'code' => 'TZ', 'currency_code' => 'TZS', 'region' => 'Africa', 'capital' => 'Dodoma', 'latitude' => -6, 'longitude' => 35],
            ['id' => 66, 'name' => 'Uganda', 'code' => 'UG', 'currency_code' => 'UGX', 'region' => 'Africa', 'capital' => 'Kampala', 'latitude' => 1, 'longitude' => 32],
            ['id' => 67, 'name' => 'Zimbabwe', 'code' => 'ZW', 'currency_code' => 'ZMW', 'region' => 'Africa', 'capital' => 'Harare', 'latitude' => -20, 'longitude' => 30],
            ['id' => 68, 'name' => 'Zambia', 'code' => 'ZM', 'currency_code' => 'ZMW', 'region' => 'Africa', 'capital' => 'Lusaka', 'latitude' => -15, 'longitude' => 30],
            ['id' => 69, 'name' => 'Senegal', 'code' => 'SN', 'currency_code' => 'XOF', 'region' => 'Africa', 'capital' => 'Dakar', 'latitude' => 14, 'longitude' => -14],
            ['id' => 70, 'name' => 'Cameroon', 'code' => 'CM', 'currency_code' => 'XAF', 'region' => 'Africa', 'capital' => 'Yaoundé', 'latitude' => 6, 'longitude' => 12],
            ['id' => 71, 'name' => 'Angola', 'code' => 'AO', 'currency_code' => 'AOA', 'region' => 'Africa', 'capital' => 'Luanda', 'latitude' => -12.5, 'longitude' => 18.5],
            ['id' => 72, 'name' => 'Mozambique', 'code' => 'MZ', 'currency_code' => 'MZN', 'region' => 'Africa', 'capital' => 'Maputo', 'latitude' => -18.25, 'longitude' => 35],
            ['id' => 73, 'name' => 'Algeria', 'code' => 'DZ', 'currency_code' => 'DZD', 'region' => 'Africa', 'capital' => 'Algiers', 'latitude' => 28, 'longitude' => 3],
            ['id' => 74, 'name' => 'Tunisia', 'code' => 'TN', 'currency_code' => 'TND', 'region' => 'Africa', 'capital' => 'Tunis', 'latitude' => 34, 'longitude' => 9],
            ['id' => 75, 'name' => 'Libya', 'code' => 'LY', 'currency_code' => 'LYD', 'region' => 'Africa', 'capital' => 'Tripoli', 'latitude' => 25, 'longitude' => 17],
            ['id' => 76, 'name' => 'Iceland', 'code' => 'IS', 'currency_code' => 'ISK', 'region' => 'Europe', 'capital' => 'Reykjavík', 'latitude' => 65, 'longitude' => -18],
            ['id' => 77, 'name' => 'Luxembourg', 'code' => 'LU', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Luxembourg', 'latitude' => 49.75, 'longitude' => 6.1666],
            ['id' => 78, 'name' => 'Malta', 'code' => 'MT', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Valletta', 'latitude' => 35.8333, 'longitude' => 14.5833],
            ['id' => 79, 'name' => 'Cyprus', 'code' => 'CY', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Nicosia', 'latitude' => 35, 'longitude' => 33],
            ['id' => 80, 'name' => 'Croatia', 'code' => 'HR', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Zagreb', 'latitude' => 45.1666, 'longitude' => 15.5],
            ['id' => 81, 'name' => 'Serbia', 'code' => 'RS', 'currency_code' => 'RSD', 'region' => 'Europe', 'capital' => 'Belgrade', 'latitude' => 44, 'longitude' => 21],
            ['id' => 82, 'name' => 'Bulgaria', 'code' => 'BG', 'currency_code' => 'BGN', 'region' => 'Europe', 'capital' => 'Sofia', 'latitude' => 43, 'longitude' => 25],
            ['id' => 83, 'name' => 'Slovakia', 'code' => 'SK', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Bratislava', 'latitude' => 48.6666, 'longitude' => 19.5],
            ['id' => 84, 'name' => 'Slovenia', 'code' => 'SI', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Ljubljana', 'latitude' => 46.1166, 'longitude' => 14.8166],
            ['id' => 85, 'name' => 'Lithuania', 'code' => 'LT', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Vilnius', 'latitude' => 56, 'longitude' => 24],
            ['id' => 86, 'name' => 'Latvia', 'code' => 'LV', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Riga', 'latitude' => 57, 'longitude' => 25],
            ['id' => 87, 'name' => 'Estonia', 'code' => 'EE', 'currency_code' => 'EUR', 'region' => 'Europe', 'capital' => 'Tallinn', 'latitude' => 59, 'longitude' => 26],
            ['id' => 88, 'name' => 'Georgia', 'code' => 'GE', 'currency_code' => 'GEL', 'region' => 'Asia', 'capital' => 'Tbilisi', 'latitude' => 42, 'longitude' => 43.5],
            ['id' => 89, 'name' => 'Armenia', 'code' => 'AM', 'currency_code' => 'AMD', 'region' => 'Asia', 'capital' => 'Yerevan', 'latitude' => 40, 'longitude' => 45],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(['id' => $country['id']], $country);
        }
    }
}